server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name __SERVER_NAME__;

    include /etc/nginx/sitectl-includes/acme-challenge.conf;
    include /etc/nginx/sitectl-includes/__SITE_NAME__.ssl.conf;

    location / {
        default_type text/plain;
        return 200 "https://__SERVER_NAME__ is prepared!\n";
    }
}
