server {
    listen 80;
    listen [::]:80;
    server_name __SERVER_NAME__;

    root /var/www/__SITE_NAME__;
    index index.html;

    include /etc/nginx/sitectl-includes/acme-challenge.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
