ssl_certificate     /etc/letsencrypt/live/__SITE_NAME__/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/__SITE_NAME__/privkey.pem;
include             /etc/letsencrypt/options-ssl-nginx.conf;
ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
